GET https://proxy.finance.qq.com/cgi/cgi-bin/rank/pt/getRank?count=40&offset=0&direct=down&board_type=hy2&sort_type=PriceRatio&r=29769&_rndtime=1712536468&_appName=ios&_dev=iPhone11,8&_devId=c55c8b27c2d4632724936a75b0ff8a74f874395d&_appver=11.14.0&_ifChId=&_isChId=1&_osVer=17.3.1&openid=oA0GbjrmFxO9Frxp3QvMbwg9_Y1k&fskey=v0b94ccfa2566133954888a265ec7394&appid=wxcbc3ab3807acb685&access_token=&buildType=store&check=11&_idfa=&lang=zh_CN&_ui=c55c8b27c2d4632724936a75b0ff8a74f874395d

### 获取行业榜单
GET https://proxy.finance.qq.com/cgi/cgi-bin/rank/pt/getRank?direct=down&board_type=hy2&sort_type=PriceRatio

### 获取股票榜单
GET https://proxy.finance.qq.com/cgi/cgi-bin/rank/hs/getBoardRankList?board_code=aStock&sort_type=priceRatio&direct=down

###
GET https://proxy.finance.qq.com/cgi/cgi-bin/rank/hs/getBoardRankList?board_code=aStock&sort_type=priceRatio&direct=down&offset=0&count=40&label_scene=limit&_rndtime=1713450196&_appName=ios&_dev=iPhone11,8&_devId=c55c8b27c2d4632724936a75b0ff8a74f874395d&_appver=11.14.0&_ifChId=&_isChId=1&_osVer=17.4.1&openid=oA0GbjrmFxO9Frxp3QvMbwg9_Y1k&fskey=v0b94ccfa2566133954888a265ec7394&appid=wxcbc3ab3807acb685&access_token=&buildType=store&check=11&_idfa=&lang=zh_CN&_ui=c55c8b27c2d4632724936a75b0ff8a74f874395d

###
GET https://proxy.finance.qq.com/cgi/cgi-bin/rank/pt/getRank?count=40&offset=0&direct=down&board_type=hy2&sort_type=PriceRatio&r=19658&_rndtime=1713450279&_appName=ios&_dev=iPhone11,8&_devId=c55c8b27c2d4632724936a75b0ff8a74f874395d&_appver=11.14.0&_ifChId=&_isChId=1&_osVer=17.4.1&openid=oA0GbjrmFxO9Frxp3QvMbwg9_Y1k&fskey=v0b94ccfa2566133954888a265ec7394&appid=wxcbc3ab3807acb685&access_token=&buildType=store&check=11&_idfa=&lang=zh_CN&_ui=c55c8b27c2d4632724936a75b0ff8a74f874395d

###
GET https://proxy.finance.qq.com/cgi/cgi-bin/stockinfoquery/kline/app/get?added=false&ktype=day&fqtype=&limit=650&toDate=2020-02-10&warrant=false&code=pt01801731&stockType=BK-HY-2&fund=false&_rndtime=1713480565&_appName=ios&_dev=iPhone11,8&_devId=c55c8b27c2d4632724936a75b0ff8a74f874395d&_appver=11.14.0&_ifChId=&_isChId=1&_osVer=17.4.1&openid=oA0GbjrmFxO9Frxp3QvMbwg9_Y1k&fskey=v0b94ccfa2566133954888a265ec7394&appid=wxcbc3ab3807acb685&access_token=&buildType=store&check=11&_idfa=&lang=zh_CN&_ui=c55c8b27c2d4632724936a75b0ff8a74f874395d

### 
GET https://proxy.finance.qq.com/cgi/cgi-bin/stockinfoquery/kline/app/get?ktype=day&limit=1&code=pt01801731&

###
POST   https://bisheng.tenpay.com/fcgi-bin/xg_plate_stocks.fcgi?_rndtime=1713556092&_appName=ios&_dev=iPhone11,8&_devId=c55c8b27c2d4632724936a75b0ff8a74f874395d&_appver=11.14.0&_ifChId=&_isChId=1&_osVer=17.4.1&openid=oA0GbjrmFxO9Frxp3QvMbwg9_Y1k&fskey=v0b94ccfa2566133954888a265ec7394&appid=wxcbc3ab3807acb685&access_token=&buildType=store&check=11&_idfa=&lang=zh_CN&_ui=c55c8b27c2d4632724936a75b0ff8a74f874395d

user_type=4&limit=100&stocks_type=3&sort_field=change_percent&exchange=12&plate_level=2&source=zxg&time=1713556092.588924&need_brief=1&sort_type=1&sign=ef6bb78dcaad5d038ffd9ec9aa497f8c&offset=0&plate_code=01801032

###
POST   https://bisheng.tenpay.com/fcgi-bin/xg_plate_stocks.fcgi
user_type=4&limit=100&stocks_type=3&sort_field=change_percent&exchange=12&plate_level=2&source=zxg&time=1713556092.588924&need_brief=1&sort_type=1&sign=ef6bb78dcaad5d038ffd9ec9aa497f8c&offset=0&plate_code=01801032

###
GET https://bisheng.tenpay.com/fcgi-bin/xg_plate_stocks.fcgi?source=zxg&sign=ef6bb78dcaad5d038ffd9ec9aa497f8c

###
POST https://bisheng.tenpay.com/fcgi-bin/xg_plate_stocks.fcgi

plate_code=01801744&plate_level=2&sort_field=change_percent&limit=7&exchange=12&stocks_type=3&sort_type=1&sign=f64d0848f4280e59683ed39e1a350ade&need_brief=1&offset=0&time=1713599041.875299&user_type=4&source=zxg

###
GET  https://proxy.finance.qq.com/ifzqgtimg/appstock/app/stockinfo/plate?code=sz002772&_appver=11.14.0

### 
GET https://proxy.finance.qq.com/ifzqgtimg/appstock/app/stockinfo/plate?code=sz002772&zdf=1&buildType=store&check=-1

###
GET https://proxy.finance.qq.com/cgi/cgi-bin/stockinfoquery/kline/app/get?added=false&ktype=day&fqtype=&limit=370&toDate=&warrant=false&code=pt01801726&stockType=BK-HY-2&fund=false&_rndtime=1713665977&_appName=ios&_dev=iPhone11,8&_devId=c55c8b27c2d4632724936a75b0ff8a74f874395d&_appver=11.14.0&_ifChId=&_isChId=1&_osVer=17.4.1&openid=anonymous&fskey=anonymous&appid=&access_token=&buildType=store&check=-1&_idfa=&lang=zh_CN&_ui=c55c8b27c2d463272493