apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    key: value 
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    env:
    - name: key
      value: name
