---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webapp.localhost
  resources:
  - learns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.localhost
  resources:
  - learns/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.localhost
  resources:
  - learns/status
  verbs:
  - get
  - patch
  - update
