# This rule is not used by the project smq itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the smq.localhost.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: smq
    app.kubernetes.io/managed-by: kustomize
  name: smq-editor-role
rules:
- apiGroups:
  - smq.localhost
  resources:
  - smqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - smq.localhost
  resources:
  - smqs/status
  verbs:
  - get
