# This rule is not used by the project smq itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to smq.localhost resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: smq
    app.kubernetes.io/managed-by: kustomize
  name: smq-viewer-role
rules:
- apiGroups:
  - smq.localhost
  resources:
  - smqs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - smq.localhost
  resources:
  - smqs/status
  verbs:
  - get
