# permissions for end users to edit examplea.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: opex
    app.kubernetes.io/managed-by: kustomize
  name: examplea-editor-role
rules:
- apiGroups:
  - example.linkinstars.com
  resources:
  - examplea
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.linkinstars.com
  resources:
  - examplea/status
  verbs:
  - get
